DEFAULT_CATEGORIES = [
    {
        "name_ru": "Электроника",
        "name_uk": "Електроніка",
        "slug": "electronics",
        "sort_order": 100,
        "is_service": False,
    },
    {
        "name_ru": "Электронные компоненты",
        "name_uk": "Електронні компоненти",
        "slug": "electronic-components",
        "sort_order": 200,
        "is_service": False,
    },
    {
        "name_ru": "Телефоны",
        "name_uk": "Телефони",
        "slug": "phones",
        "sort_order": 300,
        "is_service": False,
    },
    {
        "name_ru": "Ноутбуки",
        "name_uk": "Ноутбуки",
        "slug": "laptops",
        "sort_order": 400,
        "is_service": False,
    },
    {
        "name_ru": "Компьютеры",
        "name_uk": "Комп'ютери",
        "slug": "computers",
        "sort_order": 500,
        "is_service": False,
    },
    {
        "name_ru": "Фото и видео",
        "name_uk": "Фото та відео",
        "slug": "photo-video",
        "sort_order": 600,
        "is_service": False,
    },
    {
        "name_ru": "Медицина",
        "name_uk": "Медицина",
        "slug": "medicine",
        "sort_order": 700,
        "is_service": False,
    },
    {
        "name_ru": "Оборудование",
        "name_uk": "Обладнання",
        "slug": "equipment",
        "sort_order": 800,
        "is_service": False,
    },
    {
        "name_ru": "Инструменты",
        "name_uk": "Інструменти",
        "slug": "tools",
        "sort_order": 900,
        "is_service": False,
    },
    {
        "name_ru": "Бытовая техника",
        "name_uk": "Побутова техніка",
        "slug": "home-appliances",
        "sort_order": 1000,
        "is_service": False,
    },
    {
        "name_ru": "Авто, мото и вело",
        "name_uk": "Авто, мото та вело",
        "slug": "auto-moto-velo",
        "sort_order": 1100,
        "is_service": False,
    },
    {
        "name_ru": "Дом и сад",
        "name_uk": "Дім та сад",
        "slug": "home-garden",
        "sort_order": 1200,
        "is_service": False,
    },
    {
        "name_ru": "Одежда",
        "name_uk": "Одяг",
        "slug": "clothing",
        "sort_order": 1300,
        "is_service": False,
    },
    {
        "name_ru": "Коллекционирование",
        "name_uk": "Колекціонування",
        "slug": "collectibles",
        "sort_order": 1400,
        "is_service": False,
    },
    {
        "name_ru": "Книги",
        "name_uk": "Книги",
        "slug": "books",
        "sort_order": 1500,
        "is_service": False,
    },
    {
        "name_ru": "Спорт",
        "name_uk": "Спорт",
        "slug": "sport",
        "sort_order": 1600,
        "is_service": False,
    },
    {
        "name_ru": "3D печать",
        "name_uk": "3D друк",
        "slug": "3d-printing",
        "sort_order": 1700,
        "is_service": False,
    },

    {
        "name_ru": "Музыкальные инструменты",
        "name_uk": "Музичні інструменти",
        "slug": "musical-instruments",
        "sort_order": 1650,
        "is_service": False,
    },
    {
        "name_ru": "Канцтовары",
        "name_uk": "Канцтовари",
        "slug": "stationery",
        "sort_order": 1660,
        "is_service": False,
    },
    {
        "name_ru": "Красота и уход",
        "name_uk": "Краса та догляд",
        "slug": "personal-care",
        "sort_order": 1670,
        "is_service": False,
    },

    {
        "name_ru": "Разное",
        "name_uk": "Різне",
        "slug": "other",
        "sort_order": 1800,
        "is_service": False,
    },
    {
        "name_ru": "Услуги",
        "name_uk": "Послуги",
        "slug": "services",
        "sort_order": 1900,
        "is_service": True,
    },
]
