# app/constants/default_categories.py

DEFAULT_CATEGORIES = [
    {
        "name_ru": "Электроника",
        "name_uk": "Електроніка",
        "slug": "electronics",
        "sort_order": 100,
        "is_service": False,
        "children": [
            ("Телевизоры", "Телевізори", "televisions"),
            ("Аудиотехника", "Аудіотехніка", "audio"),
            ("Видеотехника", "Відеотехніка", "video"),
            ("Сетевое оборудование", "Мережеве обладнання", "network"),
            ("Умный дом", "Розумний дім", "smart-home"),
            ("Измерительная техника", "Вимірювальна техніка", "measurement"),
            ("Кабели и переходники", "Кабелі та перехідники", "cables"),
            ("Запчасти", "Запчастини", "electronics-parts"),
        ],
    },
    {
        "name_ru": "Электронные компоненты",
        "name_uk": "Електронні компоненти",
        "slug": "electronic-components",
        "sort_order": 200,
        "is_service": False,
        "children": [
            ("Микросхемы", "Мікросхеми", "ic"),
            ("Транзисторы", "Транзистори", "transistors"),
            ("Диоды", "Діоди", "diodes"),
            ("Резисторы", "Резистори", "resistors"),
            ("Конденсаторы", "Конденсатори", "capacitors"),
            ("Индуктивности", "Індуктивності", "inductors"),
            ("Реле", "Реле", "relays"),
            ("Разъёмы", "Роз'єми", "connectors"),
            ("Дисплеи", "Дисплеї", "displays"),
            ("Датчики", "Датчики", "sensors"),
            ("Модули", "Модулі", "modules"),
            ("Источники питания", "Джерела живлення", "power-supplies"),
            ("Печатные платы", "Друковані плати", "pcb"),
            ("Наборы и комплекты", "Набори та комплекти", "kits"),
            ("Разное", "Різне", "misc"),
        ],
    },
    {
        "name_ru": "Компьютеры",
        "name_uk": "Комп'ютери",
        "slug": "computers",
        "sort_order": 300,
        "is_service": False,
        "children": [
            ("Ноутбуки", "Ноутбуки", "laptops"),
            ("Настольные ПК", "Настільні ПК", "desktop-pc"),
            ("Мониторы", "Монітори", "monitors"),
            ("Серверы", "Сервери", "servers"),
            ("Комплектующие", "Комплектуючі", "components"),
            ("Периферия", "Периферія", "peripherals"),
            ("Запчасти", "Запчастини", "computer-parts"),
        ],
    },
    {
        "name_ru": "Телефоны",
        "name_uk": "Телефони",
        "slug": "phones",
        "sort_order": 400,
        "is_service": False,
        "children": [
            ("Смартфоны", "Смартфони", "smartphones"),
            ("Кнопочные телефоны", "Кнопкові телефони", "feature-phones"),
            ("Защищённые телефоны", "Захищені телефони", "rugged-phones"),
            ("Спутниковые телефоны", "Супутникові телефони", "satellite-phones"),
            ("Аккумуляторы", "Акумулятори", "batteries"),
            ("Дисплеи", "Дисплеї", "phone-displays"),
            ("Чехлы и аксессуары", "Чохли та аксесуари", "phone-accessories"),
            ("Запчасти", "Запчастини", "phone-parts"),
            ("Разное", "Різне", "misc"),
        ],
    },
    {
        "name_ru": "Фото и видео",
        "name_uk": "Фото та відео",
        "slug": "photo-video",
        "sort_order": 500,
        "is_service": False,
        "children": [
            ("Фотоаппараты", "Фотоапарати", "cameras"),
            ("Видеокамеры", "Відеокамери", "video-cameras"),
            ("Объективы", "Об'єктиви", "lenses"),
            ("Освещение", "Освітлення", "lighting"),
            ("Штативы", "Штативи", "tripods"),
            ("Аксессуары", "Аксесуари", "accessories"),
            ("Запчасти", "Запчастини", "photo-parts"),
        ],
    },
    {
        "name_ru": "Медицина",
        "name_uk": "Медицина",
        "slug": "medicine",
        "sort_order": 600,
        "is_service": False,
        "children": [
            ("Стоматология", "Стоматологія", "dentistry"),
            ("Лабораторное оборудование", "Лабораторне обладнання", "laboratory"),
            ("Микроскопы", "Мікроскопи", "microscopes"),
            ("Хирургия", "Хірургія", "surgery"),
            ("Инструменты", "Інструменти", "medical-tools"),
            ("Расходные материалы", "Витратні матеріали", "consumables"),
            ("Запчасти", "Запчастини", "medical-parts"),
        ],
    },
    {
        "name_ru": "3D печать",
        "name_uk": "3D друк",
        "slug": "3d-printing",
        "sort_order": 700,
        "is_service": False,
        "children": [
            ("3D принтеры", "3D принтери", "3d-printers"),
            ("Фотополимерная смола", "Фотополімерна смола", "resin"),
            ("Филамент", "Філамент", "filament"),
            ("Моечные станции", "Мийні станції", "wash-stations"),
            ("УФ камеры", "УФ камери", "uv-chambers"),
            ("Инструменты", "Інструменти", "3d-tools"),
            ("Расходные материалы", "Витратні матеріали", "3d-consumables"),
            ("Запчасти", "Запчастини", "3d-parts"),
        ],
    },
    {
        "name_ru": "Инструменты",
        "name_uk": "Інструменти",
        "slug": "tools",
        "sort_order": 800,
        "is_service": False,
        "children": [
            ("Электроинструмент", "Електроінструмент", "power-tools"),
            ("Ручной инструмент", "Ручний інструмент", "hand-tools"),
            ("Измерительный инструмент", "Вимірювальний інструмент", "measurement-tools"),
            ("Станки", "Верстати", "machines"),
            ("Оснастка", "Оснащення", "equipment"),
            ("Расходные материалы", "Витратні матеріали", "tool-consumables"),
            ("Запчасти", "Запчастини", "tool-parts"),
        ],
    },
    {
        "name_ru": "Авто, мото и вело",
        "name_uk": "Авто, мото та вело",
        "slug": "auto-moto-velo",
        "sort_order": 900,
        "is_service": False,
        "children": [
            ("Запчасти", "Запчастини", "parts"),
            ("Электроника", "Електроніка", "electronics"),
            ("Инструменты", "Інструменти", "tools"),
            ("Шины и диски", "Шини та диски", "wheels"),
            ("Аксессуары", "Аксесуари", "accessories"),
            ("Разное", "Різне", "misc"),
        ],
    },
    {
        "name_ru": "Дом и сад",
        "name_uk": "Дім та сад",
        "slug": "home-garden",
        "sort_order": 1000,
        "is_service": False,
        "children": [],
    },
    {
        "name_ru": "Одежда",
        "name_uk": "Одяг",
        "slug": "clothing",
        "sort_order": 1100,
        "is_service": False,
        "children": [],
    },
    {
        "name_ru": "Коллекционирование",
        "name_uk": "Колекціонування",
        "slug": "collectibles",
        "sort_order": 1200,
        "is_service": False,
        "children": [],
    },
    {
        "name_ru": "Книги",
        "name_uk": "Книги",
        "slug": "books",
        "sort_order": 1300,
        "is_service": False,
        "children": [],
    },
    {
        "name_ru": "Спорт",
        "name_uk": "Спорт",
        "slug": "sport",
        "sort_order": 1400,
        "is_service": False,
        "children": [],
    },
    {
        "name_ru": "Разное",
        "name_uk": "Різне",
        "slug": "other",
        "sort_order": 1500,
        "is_service": False,
        "children": [],
    },
    {
        "name_ru": "Услуги",
        "name_uk": "Послуги",
        "slug": "services",
        "sort_order": 1600,
        "is_service": True,
        "children": [
            ("Ремонт", "Ремонт", "repair"),
            ("Диагностика", "Діагностика", "diagnostics"),
            ("Монтаж", "Монтаж", "installation"),
            ("Демонтаж", "Демонтаж", "dismantling"),
            ("Обслуживание", "Обслуговування", "maintenance"),
            ("Консультации", "Консультації", "consulting"),
            ("Обучение", "Навчання", "training"),
            ("Проектирование", "Проєктування", "design"),
            ("3D моделирование", "3D моделювання", "3d-modeling"),
            ("3D печать на заказ", "3D друк на замовлення", "3d-printing-service"),
            ("Фрезеровка", "Фрезерування", "milling"),
            ("Лазерная резка", "Лазерне різання", "laser-cutting"),
            ("Перевозки", "Перевезення", "transport"),
            ("Аренда оборудования", "Оренда обладнання", "equipment-rental"),
            ("Другое", "Інше", "other"),
        ],
    },
]